---
language: python

services:
  - docker
  - postgresql
  - redis

env:
  global:
    - MY_ENV_VARIABLE=HEROKU_SECRETS
    
before_install:
  - echo "Setting up before installation..."

install:
   - echo "Building Docker Image..."
   - docker build -t travisci/worker .
   - echo "Docker Image Built Successfully"
